apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: skaffold-gitops
build:
  artifacts:
    - image: long9725/hae-argocd
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
    - service.yaml
